#pragma once

#define AERIAL_PERSPECTIVE_LUT_ATMOSPHERE_ARGS       0
#define AERIAL_PERSPECTIVE_LUT_TRANSMITTANCE_INPUT   1
#define AERIAL_PERSPECTIVE_LUT_MULTISCATTERING_INPUT 2
#define AERIAL_PERSPECTIVE_LUT_SAMPLER               3
#define AERIAL_PERSPECTIVE_LUT_OUTPUT                4
