#!/usr/bin/env bash

set -euo pipefail

xwin_root="${DXVK_XWIN_ROOT:-${XDG_CACHE_HOME:-${HOME}/.cache}/xwin/dxvk-remix}"

exec /usr/bin/lld-link "$@" \
  /nodefaultlib:boost_python310-clangw22-mt-x64-1_76.lib \
  "/libpath:${xwin_root}/crt/lib/x86_64" \
  "/libpath:${xwin_root}/sdk/lib/ucrt/x86_64" \
  "/libpath:${xwin_root}/sdk/lib/um/x86_64"
